"""Phase C lens: token conservation between consecutive API calls (Phase B split).

Question. Between two consecutive API calls of one conversation thread, the provider-reported prompt size grows by the
tokens of what was appended in between: the previous response (text, tool-call args, thinking) and the model-visible
inputs (tool results, user / system text). The log records both the usage numbers and the appended text. How tightly do
they agree, what breaks the agreement, and how large a change to ONE logged tool result would stand out above the
honest residual at a 1% false-positive rate?

Reads only IR caches analysis/cache/<corpus>_B.parquet (swechat, cc_local, aiv_cc, aiv_cu) plus
analysis/cache/swechat_population.parquet (format per session). No text leaves this script: only lengths/counts of
substrings are computed (cc_local is private; outputs are aggregates; its MCP tool names are collapsed to 'mcp__*' as in
its build report). Writes RAW COUNTS ONLY to
analysis/out/phase_c/token_conservation.json. Interpretation: analysis/notes/token_conservation.md.

Run:  PYTHONIOENCODING=utf-8 python -m analysis.probes.phase_c_token_conservation
Env:  TC_PAIRS_CACHE=<dir>  optional scratch dir to cache the extracted pair table between runs (never under data/).

Definitions (fixed in PREREG below before any residual was computed):
  unit         'fmt' = corpus x log format: swechat:claude_code, swechat:codex, swechat:opencode, swechat:gemini,
               cc_local:claude_code, aiv_cc:claude_code, aiv_cu:anthropic, aiv_cu:gemini.
  thread       one conversation context: main thread, or one subagent (agent_id / parent_call_id) within a session.
  API call     one usage per (session_id, api_msg_id) (USAGE DEDUPE rule, lib/ir.py); usage_out = max over its rows.
  context C    Anthropic-style usage (claude_code formats, opencode, aiv_cu anthropic): input + cache_read + cache_create.
               OpenAI/Gemini-style usage (codex, gemini, aiv_cu gemini): input (already includes cached tokens).
  generated    events of kind assistant/call belonging to the call: same api_msg_id; Codex (no per-item id): the
               assistant/call events between the previous usage row and this call's usage row.
  start_k      smallest seq of any event of call k (Codex: of its generated events, else its usage row).
  window k     events with start_k < seq < start_{k+1} in the thread that are not generated by call k: the inputs
               appended before call k+1 (results, user, system) plus meta markers (compaction etc.).
  dC           C_{k+1} - C_k for consecutive calls k, k+1 of one thread.
"""
import hashlib, json, os, sys, time
from collections import Counter, defaultdict

import numpy as np
import pandas as pd
import pyarrow.parquet as pq
import pyarrow.compute as pc

from analysis.lib import stats

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CACHE = os.path.join(ROOT, "analysis", "cache")
OUT = os.path.join(ROOT, "analysis", "out", "phase_c", "token_conservation.json")
SEED = stats.SEED

PREREG = {
    "split": "Phase B caches only (swechat_B, cc_local_B, aiv_cc_B, aiv_cu_B); A split not read.",
    "context_measure": {
        "anthropic_style": "usage_in + usage_cache_read + usage_cache_create (claude_code formats, opencode, aiv_cu anthropic)",
        "includes_cache_style": "usage_in (codex: last_token_usage.input_tokens; gemini CLI / aiv_cu gemini: promptTokenCount)",
        "check": "cache_read <= usage_in is counted for includes_cache formats; opencode is checked by both readings"},
    "zero_context": "API calls with C == 0 are dropped from pairs (counted).",
    "break_flags": {
        "compaction": "window holds a compaction marker: CC system compact_boundary; codex compacted / context_compacted; "
                      "opencode part compaction; or a system text starting 'This session is being continued'",
        "microcompact": "window holds a CC system microcompact_boundary",
        "image": ">=1 image marker ('[image]' or '[IMAGE_REMOVED]') in window text or call-k text (aiv_cu: not used, see aiv_cu)",
        "user_turn": "window holds a kind=user event (human prompt): thinking-retention rules change at human turns",
        "model_switch": "model of call k != model of call k+1",
        "api_error": "window holds a CC system api_error meta event",
        "foreign_generated": "window holds an assistant/call event not assigned to call k (unaligned stream)",
        "member_switch": "cc_local: extra.family_member differs between call k and call k+1 (resumed file of a family)",
        "attachment_unavailable": "cc_local/swechat CC: a visible attachment whose text was not recorded (text_source unavailable)",
        "clean": "none of the flags above"},
    "descriptive_flags_not_excluded": ["cache_read_drop (anthropic-style: cr_{k+1} < cr_k)",
                                       "cache_chain_exact (cr_{k+1} == cr_k + cc_k)",
                                       "persisted_output (result text starts '<persisted-output>')",
                                       "redaction (substring 'REDACTED' in window text)", "subagent_result (tool 'subagent')",
                                       "error_result (native_error True)", "thinking_redacted (thinking-only block with 0 chars)",
                                       "dC < 0"],
    "models": {
        "M_chars": "dC ~ result_chars + system_chars + user_chars + assistant_chars + args_chars + thinking_chars + "
                   "n_calls + n_results + n_system + intercept (OLS, clean pairs)",
        "M_out": "dC - out_k ~ result_chars + system_chars + user_chars + n_calls + n_results + n_system + intercept "
                 "(OLS, clean pairs): uses the provider's output-token count for call k instead of its chars",
        "aiv_cu_gemini_text": "dTEXT ~ same terms as M_chars on promptTokensDetails.TEXT; dIMAGE analysed separately",
        "cross_fit": "2 folds by md5(session_id) parity; every residual is out-of-fold (fit on the other fold)"},
    "detector": {
        "fpr": 0.01,
        "D_abs": "flag a pair when |residual| > T, T = 0.99 quantile of |out-of-fold residual| over clean pairs of the OTHER fold",
        "D_bin": "same, T per bin of logged window non-generated chars, bins [0,1e2,1e3,1e4,1e5,inf) (logged = tampered value)",
        "tamper": "replace the LARGEST result in the window by text whose length differs by delta chars (delta>0 longer, "
                  "delta<0 shorter, delta >= -len(result)); predicted dC shifts by beta_result * delta; actual dC unchanged",
        "delta_grid": "log-spaced 10**(i/20) for i=0..120 (1 .. 1e6 chars), both signs",
        "power_targets": [0.5, 0.9],
        "assumption": "substituted text tokenizes at the fitted chars/token of results (beta_result)"},
    "min_pairs": {"per_model_fit": 500, "per_tool": 100, "per_flag": 30},
    "bins_result_chars": [0, 100, 1000, 10000, 100000, float("inf")],
}
POST_HOC = {
    "M_hyb_primary": {
        "rule": "primary model M_hyb: dC ~ res_chars + res_nl + res_nonascii_bytes + n_results + res_stderr_chars(aiv_cu only) + "
                "sys_chars + n_system + F*out_k + F*reasoning_tokens_k + F + (1-F)*(assistant_chars, args_chars, thinking_chars, "
                "n_calls) + intercept, F = out_final = (out_k > 0 and generated chars <= 6 * out_k)",
        "why_added": "in-sample exploratory fits of the pre-registered M_chars / M_out showed (a) the logged output_tokens of Claude Code "
                     "calls is a streaming partial (<= 10) in 29% of swechat CC, 19% of cc_local and 89% of aiv_cc clean pairs, so "
                     "M_out fails there; (b) cc_local thinking blocks are logged with 0 chars in 66% of clean pairs, so M_chars "
                     "fails there. M_hyb uses the token count when it is plausible from the call's own logged chars, else chars. "
                     "F uses only call k's own log fields, never dC. M_chars and M_out are still reported (cross-fitted).",
        "reporting": "models.<fmt>.{M_hyb,M_chars,M_out}"},
    "huber": {"rule": "all fits are Huber IRLS (c = 1.345 x 1.4826 x MAD of residuals, <= 50 iterations) instead of OLS",
              "why_added": "exploratory OLS coefficients were pulled by heavy tails (e.g. n_calls vs n_results +-3000 tokens, "
                           "collinear); residual quantiles are reported for every pair, so robust fitting only changes the centre"},
    "collinear_counts": {"rule": "n_results enters every model; n_calls only in the chars regime (1-F)",
                         "why_added": "n_calls == n_results in almost every clean pair (exploratory coefficients +-3000)"},
    "res_shape_terms": {"rule": "res_nl (newline count) and res_nonascii (utf-8 bytes - chars) of window results added to M_hyb",
                        "why_added": "Read results are line-numbered and some outputs are non-ASCII; both change chars/token. "
                                     "Both are computed from the logged text only"},
    "codex_large_result": {"rule": "break flag (excluded from clean): swechat:codex window whose largest result > 40,000 chars",
                           "why_added": "exploratory binned table showed dC - out_k saturating near 11.6k tokens for single "
                                        "results above ~60k chars (the model sees a truncated output; the log keeps it all). "
                                        "Reported in codex_saturation"},
    "tool_aware": {"rule": "detection_M_hyb_by_tool: pairs whose window results all come from one tool (>= 1000 clean pairs); "
                           "thresholds computed within that tool's pairs (other fold), pooled-model residuals",
                    "why_added": "per-tool |residual| p99 differed several-fold (e.g. edit vs read windows)"},
    "asym_detector": {"rule": "D_asym: flag when the residual is below the 0.005 or above the 0.995 quantile of signed out-of-fold "
                               "residuals of the other fold (two one-sided 0.5% tails)",
                       "why_added": "honest residuals are skewed (positive tail longer: the model saw more than the log); a "
                                    "symmetric |r| threshold wastes power on the short side"},
    "model_aware": {"rule": "detection_M_hyb_model_aware: residuals and rates from an M_hyb cross-fit within each model_k1 with "
                            ">= 500 clean pairs (pooled-model residual otherwise); same detector rules",
                    "why_added": "per-model residual medians differed by several hundred tokens in aiv_cu (thinking retention "
                                 "differs by model), which a pooled fit cannot absorb"},
    "tamper_rate": {"rule": "the predicted-dC shift of a tamper of delta chars uses the pair's effective rate beta_res + beta_nl * "
                            "(res_nl/res_chars) + beta_nonascii * (res_nonascii/res_chars) (replacement text has the window's "
                            "composition); beta_res alone when res_chars == 0",
                    "why_added": "follows from adding res_shape_terms"},
    "user_turn_eval": {"rule": "pairs with a human user event are scored with the clean model plus beta_res * user_chars "
                               "(user text at the result-text rate, no framing term; no user term can be fitted on clean pairs)",
                       "why_added": "clean pairs exclude user turns by definition; the fitted sys term is unstable in formats "
                                    "with few system events (first test run: opencode beta_sys = -2360 tokens/char)"},
    "min_nonzero_terms": {"rule": "a design column with fewer than 30 non-zero pairs in the fitting set is dropped (coef 0)",
                          "why_added": "first test run: opencode sys_chars fitted from a handful of pairs gave -2360 tokens/char"},
    "thinking_chars": {"rule": "think = max(thinking chars of call k's thinking-only meta rows, thinking chars on its assistant/call "
                                "events) + aiv_cu reasoning_chars",
                       "why_added": "CC thinking chars appear on both the thinking-only meta row and the next block event; the "
                                    "event-side count can carry over between calls"},
}

FMT_CTX_INCLUDES_CACHE = {"swechat:codex", "swechat:gemini", "aiv_cu:gemini"}
IMG_PATS = ("[image]", "[IMAGE_REMOVED]")


# --------------------------------------------------------------------------------------------------------------- utils
def md5_fold(s):
    return int(hashlib.md5(str(s).encode()).hexdigest(), 16) % 2


def cq(values, sids, q):
    return stats.cluster_quantile(values, sids, q)


def desc(v):
    return stats.describe(v)


def qtab(values, sids, qs=(0.5, 0.9, 0.99)):
    v = np.asarray(values, float)
    if len(v) == 0:
        return {"n": 0}
    out = {"n": int(len(v)), "n_sessions": int(len(set(sids)))}
    for q in qs:
        r = cq(v, sids, q)
        out[f"p{round(q * 100, 1):g}"] = {"value": r["value"], "lo": r["lo"], "hi": r["hi"]}
    return out


def crate(num, den, sids):
    """session-clustered rate: sum per session first."""
    d = pd.DataFrame({"s": sids, "n": np.asarray(num, float), "d": np.asarray(den, float)}).groupby("s").sum()
    return stats.cluster_rate(d["n"].values, d["d"].values)


# --------------------------------------------------------------------------------------------------------------- load
EXTRA_KEYS = ("thinking_chars", "entry_type", "subtype", "type", "attachment_type", "part_type", "reasoning_chars",
              "dup_message", "synthetic", "visibility", "text_source", "family_member", "compacted_at", "truncated",
              "role", "empty_text", "status", "sdk_usage_of_non_acting_text_message", "reasoning_output_tokens",
              "reasoning_tokens")


def parse_extra(ex):
    if not isinstance(ex, str) or not ex:
        return {}
    try:
        d = json.loads(ex)
    except Exception:
        return {}
    if not isinstance(d, dict):
        return {}
    out = {k: d.get(k) for k in EXTRA_KEYS if k in d}
    ud = d.get("usage_detail")
    if isinstance(ud, dict):
        ptd = ud.get("promptTokensDetails") or {}
        if isinstance(ptd, dict):
            out["p_text"] = ptd.get("TEXT")
            out["p_image"] = ptd.get("IMAGE")
        out["thoughts_tokens"] = ud.get("thoughtsTokenCount")
    return out


def load_corpus(corpus):
    """IR cache -> event frame with text-derived lengths/counts only (text dropped)."""
    path = os.path.join(CACHE, f"{corpus}_B.parquet")
    f = pq.ParquetFile(path)
    cols = ["session_id", "stratum", "seq", "kind", "tool", "tool_raw", "api_msg_id", "model", "is_subagent", "agent_id",
            "parent_call_id", "usage_in", "usage_out", "usage_cache_read", "usage_cache_create", "native_error", "extra"]
    frames = []
    for rg in range(f.num_row_groups):
        t = f.read_row_group(rg, columns=cols + ["text", "args", "stderr"])
        txt, args, se = t["text"], t["args"], t["stderr"]

        def ln(a):
            return pc.fill_null(pc.utf8_length(a), 0).to_numpy(zero_copy_only=False)

        def cnt(a, pat):
            return pc.fill_null(pc.count_substring(a, pat), 0).to_numpy(zero_copy_only=False)

        feat = {
            "tlen": ln(txt), "tbytes": pc.fill_null(pc.binary_length(txt), 0).to_numpy(zero_copy_only=False),
            "alen": ln(args), "slen": ln(se), "tnull": pc.is_null(txt).to_numpy(zero_copy_only=False),
            "n_img": sum(cnt(txt, p) for p in IMG_PATS) + sum(cnt(args, p) for p in IMG_PATS),
            "n_red": cnt(txt, "REDACTED") + cnt(args, "REDACTED"),
            "persisted": pc.fill_null(pc.starts_with(txt, "<persisted-output>"), False).to_numpy(zero_copy_only=False),
            "continued": pc.fill_null(pc.starts_with(txt, "This session is being continued"), False).to_numpy(zero_copy_only=False),
            "n_nl": cnt(txt, "\n"),
        }
        df = t.select(cols).to_pandas()
        for k, v in feat.items():
            df[k] = v
        frames.append(df)
        del t
    ev = pd.concat(frames, ignore_index=True)
    ex = ev["extra"].map(parse_extra)
    exdf = pd.DataFrame(list(ex.values), index=ev.index)
    ev = pd.concat([ev.drop(columns=["extra"]), exdf], axis=1)
    return ev


def fmt_of(corpus, ev):
    if corpus == "swechat":
        pop = pd.read_parquet(os.path.join(CACHE, "swechat_population.parquet"), columns=["session_id", "format"])
        m = dict(zip(pop.session_id, pop.format))
        return ev["session_id"].map(lambda s: "swechat:" + str(m.get(s)))
    if corpus == "aiv_cu":
        return ev["stratum"].map(lambda s: "aiv_cu:gemini" if str(s).startswith("gemini") else
                                 ("aiv_cu:anthropic" if str(s).startswith("anthropic") else "aiv_cu:other"))
    return pd.Series([f"{corpus}:claude_code"] * len(ev), index=ev.index)


# --------------------------------------------------------------------------------------------------------------- pairs
def thread_key(is_sub, agent_id, parent_call_id):
    if is_sub is True or (is_sub is not None and not pd.isna(is_sub) and bool(is_sub)):
        a = agent_id if isinstance(agent_id, str) else (parent_call_id if isinstance(parent_call_id, str) else "unknown")
        return "sub:" + a
    return "main"


def g(x, default=0):
    try:
        if x is None or pd.isna(x):
            return default
    except (TypeError, ValueError):
        pass
    return x


def build_pairs(ev, fmt_series, counters):
    """Return list of pair dicts for one corpus."""
    ev = ev.assign(fmt=fmt_series.values)
    ev = ev.sort_values(["session_id", "seq"], kind="stable").reset_index(drop=True)
    ev["thread"] = [thread_key(a, b, c) for a, b, c in zip(ev.is_subagent, ev.agent_id, ev.parent_call_id)]
    pairs = []
    rec = ev.to_dict("records")
    # group indices by (session, thread)
    groups = defaultdict(list)
    for i, r in enumerate(rec):
        groups[(r["session_id"], r["thread"])].append(i)
    id_thread = {}
    for (sid, th), idx in groups.items():
        fmt = rec[idx[0]]["fmt"]
        incl = fmt in FMT_CTX_INCLUDES_CACHE
        codex = fmt == "swechat:codex"
        calls = {}  # api id -> dict
        order = []
        pending_gen = []
        for i in idx:
            r = rec[i]
            aid = r["api_msg_id"] if isinstance(r["api_msg_id"], str) else None
            kind = r["kind"]
            has_u = not pd.isna(r["usage_in"]) if r["usage_in"] is not None else False
            if codex:
                if kind in ("assistant", "call"):
                    pending_gen.append(i)
                if has_u and aid:
                    if (sid, aid) in id_thread and id_thread[(sid, aid)] != th:
                        counters["api_id_in_two_threads"] += 1
                        continue
                    id_thread[(sid, aid)] = th
                    if aid not in calls:
                        calls[aid] = {"rows": [i], "gen": list(pending_gen), "usage_row": i}
                        order.append(aid)
                    else:
                        calls[aid]["rows"].append(i)
                    pending_gen = []
                continue
            if aid is None:
                continue
            if aid not in calls:
                if (sid, aid) in id_thread and id_thread[(sid, aid)] != th:
                    counters["api_id_in_two_threads"] += 1
                    continue
                calls[aid] = {"rows": [], "gen": [], "usage_row": None}
                order.append(aid)
            c = calls[aid]
            c["rows"].append(i)
            if kind in ("assistant", "call"):
                c["gen"].append(i)
            if has_u and c["usage_row"] is None:
                c["usage_row"] = i
                id_thread[(sid, aid)] = th
        # keep calls with usage
        seq_list = []
        for aid in order:
            c = calls[aid]
            if c["usage_row"] is None:
                counters["api_id_without_usage"] += 1
                continue
            u = rec[c["usage_row"]]
            urows = [rec[i] for i in c["rows"] if not pd.isna(rec[i]["usage_in"])]
            ins = {(g(x["usage_in"]), g(x["usage_cache_read"]), g(x["usage_cache_create"])) for x in urows}
            if len(ins) > 1:
                counters["api_id_usage_input_varies"] += 1
            uin, ucr, ucc = g(u["usage_in"]), g(u["usage_cache_read"]), g(u["usage_cache_create"])
            out = max(g(x["usage_out"]) for x in urows)
            C = uin if incl else uin + ucr + ucc
            if incl and ucr > uin:
                counters["includes_cache_fmt_cache_read_gt_input"] += 1
            if C == 0:
                counters["zero_context_calls"] += 1
                continue
            if codex:
                start = min([rec[i]["seq"] for i in c["gen"]] or [u["seq"]])
            else:
                start = min(rec[i]["seq"] for i in c["rows"])
            seq_list.append((start, aid, C, uin, ucr, ucc, out, u))
        seq_list.sort(key=lambda x: x[0])
        counters["calls_with_usage"] += len(seq_list)
        if len(seq_list) < 2:
            continue
        # position index for window scan
        idx_seq = [rec[i]["seq"] for i in idx]
        pos = {s: p for p, s in enumerate(idx_seq)}
        for k in range(len(seq_list) - 1):
            s0, a0, C0, in0, cr0, cc0, out0, u0 = seq_list[k]
            s1, a1, C1, in1, cr1, cc1, out1, u1 = seq_list[k + 1]
            gen_set = set(calls[a0]["gen"])
            p = dict(fmt=fmt, session_id=sid, thread=th, k=k, model_k=u0["model"], model_k1=u1["model"],
                     C_k=C0, C_k1=C1, dC=C1 - C0, out_k=out0, in_k=in0, cr_k=cr0, cc_k=cc0, in_k1=in1, cr_k1=cr1, cc_k1=cc1)
            # generated features of call k
            a_chars = a_n = arg_chars = n_calls = think = think_meta = think_zero = reason = gen_img = gen_red = 0
            for i in calls[a0]["gen"]:
                r = rec[i]
                if r["kind"] == "assistant":
                    a_chars += r["tlen"]; a_n += 1
                else:
                    arg_chars += r["alen"] + len(str(r["tool_raw"] or "")); n_calls += 1
                think += g(r.get("thinking_chars"))
                reason += g(r.get("reasoning_chars"))
                gen_img += r["n_img"]; gen_red += r["n_red"]
            for i in calls[a0]["rows"]:
                r = rec[i]
                if r.get("entry_type") == "assistant_thinking_only":
                    tc = g(r.get("thinking_chars"))
                    think_meta += tc
                    think_zero += int(tc == 0)
            p.update(gen_text_chars=a_chars, gen_text_n=a_n, gen_args_chars=arg_chars, n_calls=n_calls,
                     think_chars_ev=think, think_chars_meta=think_meta, think_zero_blocks=think_zero, reasoning_chars=reason,
                     gen_img=gen_img, gen_red=gen_red)
            # Gemini text/image split (aiv_cu)
            p["p_text_k"], p["p_image_k"] = u0.get("p_text"), u0.get("p_image")
            p["p_text_k1"], p["p_image_k1"] = u1.get("p_text"), u1.get("p_image")
            p["thoughts_k"] = u0.get("thoughts_tokens")
            rt = u0.get("reasoning_output_tokens")
            p["reason_tok_k"] = g(rt if rt is not None else u0.get("reasoning_tokens"))
            p["fam_k"], p["fam_k1"] = u0.get("family_member"), u1.get("family_member")
            # window
            res_chars = res_n = res_bytes = res_nl = res_max = res_err = res_persist = res_sub = res_stderr = 0
            res_null = 0
            user_chars = user_n = sys_chars = sys_n = att_n = att_unavail = 0
            w_img = w_red = 0
            compaction = micro = api_err = foreign = cont = 0
            tools = Counter()
            p0, p1 = pos[s0], pos[s1] if s1 in pos else len(idx)
            for q in range(p0 + 1, p1):
                r = rec[idx[q]]
                if idx[q] in gen_set:
                    continue
                kind = r["kind"]
                if kind in ("assistant", "call"):
                    if r["api_msg_id"] != a0:
                        foreign += 1
                    continue
                if kind == "result":
                    L = r["tlen"]
                    res_chars += L; res_n += 1; res_bytes += r["tbytes"]; res_nl += r["n_nl"]
                    res_max = max(res_max, L); res_err += int(r["native_error"] is True)
                    res_persist += int(bool(r["persisted"])); res_sub += int(r["tool"] == "subagent")
                    res_stderr += r["slen"]; res_null += int(bool(r["tnull"]))
                    tools[str(r["tool"])] += 1
                    w_img += r["n_img"]; w_red += r["n_red"]
                elif kind == "user":
                    user_chars += r["tlen"]; user_n += 1; w_img += r["n_img"]; w_red += r["n_red"]
                elif kind == "system":
                    sys_chars += r["tlen"]; sys_n += 1; w_img += r["n_img"]; w_red += r["n_red"]
                    cont += int(bool(r["continued"]))
                    if r.get("entry_type") == "attachment":
                        att_n += 1
                        att_unavail += int(r.get("text_source") == "unavailable")
                elif kind == "meta":
                    et, st, pt, ty = r.get("entry_type"), r.get("subtype"), r.get("part_type"), r.get("type")
                    if (et == "system" and st == "compact_boundary") or pt == "compaction" or et == "compacted" \
                            or (et == "event_msg" and ty == "context_compacted"):
                        compaction += 1
                    if et == "system" and st == "microcompact_boundary":
                        micro += 1
                    if et == "system" and st == "api_error":
                        api_err += 1
            p.update(res_chars=res_chars, res_n=res_n, res_bytes=res_bytes, res_nl=res_nl, res_max=res_max, res_err=res_err,
                     res_persist=res_persist, res_sub=res_sub, res_stderr=res_stderr, res_textnull=res_null,
                     user_chars=user_chars, user_n=user_n, sys_chars=sys_chars, sys_n=sys_n, att_n=att_n,
                     att_unavail=att_unavail, w_img=w_img, w_red=w_red, compaction=compaction + cont, microcompact=micro,
                     api_error=api_err, foreign_gen=foreign,
                     top_tool=(tools.most_common(1)[0][0] if tools else None), n_tools_distinct=len(tools))
            pairs.append(p)
    return pairs


def extract_all():
    counters = {}
    allp = []
    for corpus in ("swechat", "cc_local", "aiv_cc", "aiv_cu"):
        t0 = time.time()
        ev = load_corpus(corpus)
        fs = fmt_of(corpus, ev)
        c = Counter()
        ev_counts = ev.assign(fmt=fs.values).groupby("fmt").agg(events=("seq", "size"), sessions=("session_id", "nunique"))
        pr = build_pairs(ev, fs, c)
        counters[corpus] = {"build": dict(c), "events_by_fmt": ev_counts.to_dict("index")}
        allp.extend(pr)
        print(corpus, len(pr), "pairs", round(time.time() - t0, 1), "s", dict(c), file=sys.stderr)
        del ev
    return pd.DataFrame(allp), counters


# ------------------------------------------------------------------------------------------------------------ derive
FMTS = ["swechat:claude_code", "cc_local:claude_code", "aiv_cc:claude_code", "swechat:codex", "swechat:opencode",
        "swechat:gemini", "aiv_cu:anthropic", "aiv_cu:gemini"]
BREAK_FLAGS = ["f_compaction", "f_microcompact", "f_image", "f_user_turn", "f_model_switch", "f_api_error", "f_foreign",
               "f_member_switch", "f_att_unavailable", "f_codex_large_result"]
DESC_FLAGS = ["d_cache_read_drop", "d_cache_chain_break", "d_persisted", "d_redaction", "d_subagent_result", "d_error_result",
              "d_thinking_redacted", "d_thinking_logged", "d_subagent_thread", "d_out_not_final", "d_dC_negative"]


def derive(P):
    P = P.copy()
    for c in ("reason_tok_k", "reasoning_chars", "think_chars_meta", "think_chars_ev", "out_k"):
        P[c] = pd.to_numeric(P[c], errors="coerce").fillna(0).astype(float)
    P["think"] = np.maximum(P.think_chars_meta, P.think_chars_ev) + P.reasoning_chars
    P["gen_chars"] = P.gen_text_chars + P.gen_args_chars + P.think
    P["F"] = ((P.out_k > 0) & (P.gen_chars <= 6 * P.out_k)).astype(float)
    P["res_nonascii"] = (P.res_bytes - P.res_chars).astype(float)
    P["res_stderr_m"] = np.where(P.fmt.str.startswith("aiv_cu"), P.res_stderr, 0).astype(float)
    anth = ~P.fmt.isin(list(FMT_CTX_INCLUDES_CACHE))
    P["f_compaction"] = P.compaction > 0
    P["f_microcompact"] = P.microcompact > 0
    P["f_image"] = ((P.w_img + P.gen_img) > 0) & ~P.fmt.str.startswith("aiv_cu")
    P["f_user_turn"] = P.user_n > 0
    P["f_model_switch"] = P.model_k.fillna("").astype(str) != P.model_k1.fillna("").astype(str)
    P["f_api_error"] = P.api_error > 0
    P["f_foreign"] = P.foreign_gen > 0
    P["f_member_switch"] = pd.to_numeric(P.fam_k, errors="coerce").fillna(-1) != pd.to_numeric(P.fam_k1, errors="coerce").fillna(-1)
    P["f_att_unavailable"] = P.att_unavail > 0
    P["f_codex_large_result"] = (P.fmt == "swechat:codex") & (P.res_max > 40000)
    P["clean"] = ~P[BREAK_FLAGS].any(axis=1)
    P["d_cache_read_drop"] = anth & (P.cr_k1 < P.cr_k)
    P["d_cache_chain_break"] = anth & (P.cr_k1 != P.cr_k + P.cc_k)
    P["d_persisted"] = P.res_persist > 0
    P["d_redaction"] = (P.w_red + P.gen_red) > 0
    P["d_subagent_result"] = P.res_sub > 0
    P["d_error_result"] = P.res_err > 0
    P["d_thinking_redacted"] = P.think_zero_blocks > 0
    P["d_thinking_logged"] = P.think > 0
    P["d_subagent_thread"] = P.thread != "main"
    P["d_out_not_final"] = P.F == 0
    P["d_dC_negative"] = P.dC < 0
    P["fold"] = P.session_id.map(md5_fold).astype(int)
    # cc_local privacy (same rule as its build report): MCP tool names collapse to 'mcp__*'
    cl = (P.fmt == "cc_local:claude_code") & P.top_tool.fillna("").astype(str).str.startswith("mcp__")
    P.loc[cl, "top_tool"] = "mcp__*"
    return P


# -------------------------------------------------------------------------------------------------------------- models
def design(P, model):
    F = P.F.values
    nF = 1 - F
    cols = {}
    if model == "M_hyb":
        cols = {"res_chars": P.res_chars, "res_nl": P.res_nl, "res_nonascii": P.res_nonascii, "n_results": P.res_n,
                "res_stderr": P.res_stderr_m, "sys_chars": P.sys_chars, "n_system": P.sys_n,
                "F_out": F * P.out_k, "F_reason": F * P.reason_tok_k, "F": F,
                "nF_text": nF * P.gen_text_chars, "nF_args": nF * P.gen_args_chars, "nF_think": nF * P.think,
                "nF_calls": nF * P.n_calls}
    elif model == "M_chars":
        cols = {"res_chars": P.res_chars, "sys_chars": P.sys_chars, "text": P.gen_text_chars, "args": P.gen_args_chars,
                "think": P.think, "n_results": P.res_n, "n_system": P.sys_n}
    elif model == "M_out":
        cols = {"res_chars": P.res_chars, "sys_chars": P.sys_chars, "n_results": P.res_n, "n_system": P.sys_n}
    names = list(cols) + ["intercept"]
    A = np.column_stack([np.asarray(v, float) for v in cols.values()] + [np.ones(len(P))])
    return A, names


def target(P, model, ycol="dC"):
    y = P[ycol].values.astype(float)
    if model == "M_out":
        y = y - P.out_k.values
    return y


MIN_NONZERO = 30


def huber(A, y, iters=50):
    w = np.ones(len(y))
    keep = (A != 0).sum(0) >= MIN_NONZERO
    keep[-1] = True  # intercept
    b = np.zeros(A.shape[1])
    for _ in range(iters):
        sw = np.sqrt(w)
        bk, *_ = np.linalg.lstsq(A[:, keep] * sw[:, None], y * sw, rcond=None)
        b = np.zeros(A.shape[1])
        b[keep] = bk
        r = y - A @ b
        s = 1.4826 * np.median(np.abs(r - np.median(r)))
        c = 1.345 * max(s, 1e-9)
        wn = np.where(np.abs(r) <= c, 1.0, c / np.maximum(np.abs(r), 1e-12))
        done = np.max(np.abs(wn - w)) < 1e-6
        w = wn
        if done:
            break
    return b, w


def crossfit(P, model, ycol="dC"):
    """Out-of-fold residuals (fit on the other fold). Returns (r_oof, coef_by_fold, full coef, full weights, names, A, y)."""
    A, names = design(P, model)
    y = target(P, model, ycol)
    r = np.full(len(y), np.nan)
    coefs = {}
    fold = P.fold.values
    for f in (0, 1):
        tr, te = fold != f, fold == f
        if tr.sum() < 30 or te.sum() == 0:
            continue
        b, _ = huber(A[tr], y[tr])
        r[te] = y[te] - A[te] @ b
        coefs[f] = b
    bfull, wfull = huber(A, y)
    return r, coefs, bfull, wfull, names, A, y


def boot_coef(A, y, w, sids, names, which, n_boot=stats.N_BOOT, seed=SEED):
    """Session bootstrap of weighted LS with the full fit's Huber weights held fixed. Returns {name: (lo, hi)}."""
    keep = (A != 0).sum(0) >= MIN_NONZERO
    keep[-1] = True
    Ak = A[:, keep]
    nk = [n for n, k in zip(names, keep) if k]
    uniq, inv = np.unique(sids, return_inverse=True)
    S, p = len(uniq), Ak.shape[1]
    XtX = np.zeros((S, p, p))
    Xty = np.zeros((S, p))
    Aw = Ak * w[:, None]
    np.add.at(XtX, inv, Aw[:, :, None] * Ak[:, None, :])
    np.add.at(Xty, inv, Aw * y[:, None])
    rng = np.random.default_rng(seed)
    out = {n: [] for n in which if n in nk}
    for _ in range(n_boot):
        cnt = np.bincount(rng.integers(0, S, S), minlength=S).astype(float)
        M = np.tensordot(cnt, XtX, 1)
        v = cnt @ Xty
        b = np.linalg.lstsq(M, v, rcond=None)[0]
        for n in out:
            out[n].append(b[nk.index(n)])
    return {n: (float(np.quantile(v, 0.025)), float(np.quantile(v, 0.975))) for n, v in out.items() if v}


def coef_dict(b, names):
    return {n: float(v) for n, v in zip(names, b)}


def eff_rate(P, coef, names):
    c = dict(zip(names, coef))
    br = c.get("res_chars", 0.0)
    rc = P.res_chars.values.astype(float)
    with np.errstate(divide="ignore", invalid="ignore"):
        nl = np.where(rc > 0, P.res_nl.values / np.maximum(rc, 1), 0.0)
        na = np.where(rc > 0, P.res_nonascii.values / np.maximum(rc, 1), 0.0)
    return br + c.get("res_nl", 0.0) * nl + c.get("res_nonascii", 0.0) * na


# ----------------------------------------------------------------------------------------------------------- detection
GRID = np.array([10 ** (i / 20) for i in range(0, 121)])
REPORT_DELTAS = [100, 300, 1000, 3000, 10000, 30000, 100000]
WIN_BINS = [0, 1e2, 1e3, 1e4, 1e5, np.inf]
RES_BINS = PREREG["bins_result_chars"]


def thresholds(absr, logged_chars):
    T = float(np.quantile(absr, 0.99))
    tb = {}
    bi = np.digitize(logged_chars, WIN_BINS[1:-1])
    for b in range(len(WIN_BINS) - 1):
        m = bi == b
        tb[b] = float(np.quantile(absr[m], 0.99)) if m.sum() >= 100 else T
    return T, tb


def detect(r, shift, logged, T, tb, mode):
    if mode == "asym":
        rs = r - shift
        return (rs < tb["lo"]) | (rs > tb["hi"])
    rr = np.abs(r - shift)
    if mode == "abs":
        return rr > T
    bi = np.digitize(logged, WIN_BINS[1:-1])
    thr = np.array([tb[b] for b in range(len(WIN_BINS) - 1)])[bi]
    return rr > thr


def flags_for(r, rate, win, fold, delta, Tf, mode):
    fl = np.zeros(len(r), bool)
    for f in (0, 1):
        m = fold == f
        if m.any():
            d = delta[m] if np.ndim(delta) else delta
            fl[m] = detect(r[m], rate[m] * d, win[m] + d, Tf[f][0], Tf[f][1], mode)
    return fl


def detection(C, r, rate, sids):
    """C: clean pairs (same order as r); rate: per-pair effective tokens/char from the model of the pair's fold."""
    fold = C.fold.values
    win = (C.res_chars + C.sys_chars).values.astype(float)
    resmax = C.res_max.values.astype(float)
    ok = ~np.isnan(r) & ~np.isnan(rate)
    out = {"thresholds": {}, "realized_fpr": {}, "power": {}, "by_result_size": {}}
    Tf, Ta = {}, {}
    for f in (0, 1):
        other = ok & (fold != f)
        if other.sum() < 100:
            return {"skipped": "fewer than 100 out-of-fold residuals in a fold"}
        T, tb = thresholds(np.abs(r[other]), win[other])
        Tf[f] = (T, tb)
        Ta[f] = (T, {"lo": float(np.quantile(r[other], 0.005)), "hi": float(np.quantile(r[other], 0.995))})
        out["thresholds"][f"applied_to_fold{f}"] = {
            "T_abs": T, "T_bin": {f"[{WIN_BINS[b]:g},{WIN_BINS[b + 1]:g})": v for b, v in tb.items()},
            "T_asym": Ta[f][1], "from_n_pairs": int(other.sum())}
    TT = {"abs": Tf, "bin": Tf, "asym": Ta}
    for mode in ("abs", "bin", "asym"):
        fl = flags_for(r[ok], rate[ok], win[ok], fold[ok], 0.0, TT[mode], mode)
        out["realized_fpr"][mode] = crate(fl.astype(float), np.ones(ok.sum()), sids[ok])
    elig = ok & (C.res_n.values > 0)
    out["eligible_pairs_with_result"] = int(elig.sum())
    for mode in ("abs", "bin", "asym"):
        res = {}
        for sign in (1, -1):
            key = "longer" if sign > 0 else "shorter"
            res[key] = {"min_delta_power_0.5": None, "min_delta_power_0.9": None, "at": {}}
            for d in GRID:
                e = elig & (resmax >= d) if sign < 0 else elig
                if e.sum() < 30:
                    break
                fl = flags_for(r[e], rate[e], win[e], fold[e], sign * d, TT[mode], mode)
                pw = float(fl.mean())
                for tgt in ("0.5", "0.9"):
                    k2 = f"min_delta_power_{tgt}"
                    if res[key][k2] is None and pw >= float(tgt):
                        res[key][k2] = {"delta_chars": float(d), "power": pw, "n_pairs": int(e.sum())}
            for D in REPORT_DELTAS:
                e = elig & (resmax >= D) if sign < 0 else elig
                if e.sum() < 30:
                    res[key]["at"][str(D)] = {"n_pairs": int(e.sum())}
                    continue
                fl = flags_for(r[e], rate[e], win[e], fold[e], sign * float(D), TT[mode], mode)
                cr = crate(fl.astype(float), np.ones(len(fl)), sids[e])
                res[key]["at"][str(D)] = {"power": cr["rate"], "lo": cr["lo"], "hi": cr["hi"], "n_pairs": int(e.sum()),
                                          "n_sessions": cr["n_sessions"]}
        out["power"][mode] = res
    for b in range(len(RES_BINS) - 1):
        lo, hi = RES_BINS[b], RES_BINS[b + 1]
        sel = elig & (resmax >= lo) & (resmax < hi)
        key = f"[{lo:g},{hi:g})"
        if sel.sum() < 30:
            out["by_result_size"][key] = {"n_pairs": int(sel.sum())}
            continue
        entry = {"n_pairs": int(sel.sum()), "n_sessions": int(len(set(sids[sel]))),
                 "result_chars_median": float(np.median(resmax[sel]))}
        for mode in ("abs", "bin", "asym"):
            for sign in (1, -1):
                best = {"0.5": None, "0.9": None}
                for d in GRID:
                    e = sel & (resmax >= d) if sign < 0 else sel
                    if e.sum() < 30:
                        break
                    fl = flags_for(r[e], rate[e], win[e], fold[e], sign * d, TT[mode], mode)
                    pw = float(fl.mean())
                    for tgt in ("0.5", "0.9"):
                        if best[tgt] is None and pw >= float(tgt):
                            best[tgt] = {"delta_chars": float(d), "power": pw, "n_pairs": int(e.sum())}
                    if best["0.9"] is not None:
                        break
                entry[f"{mode}_{'longer' if sign > 0 else 'shorter'}_min_delta"] = best
            rel = {}
            for frac in (-1.0, -0.5, 0.5, 1.0, 3.0):
                delta = frac * resmax[sel]
                fl = flags_for(r[sel], rate[sel], win[sel], fold[sel], delta, TT[mode], mode)
                cr = crate(fl.astype(float), np.ones(len(fl)), sids[sel])
                rel[f"{frac:+g}"] = {"power": cr["rate"], "lo": cr["lo"], "hi": cr["hi"]}
            entry[f"{mode}_relative_change_power"] = rel
        out["by_result_size"][key] = entry
    return out


# ------------------------------------------------------------------------------------------------------------ sections
def resid_summary(r, sids, T=None):
    r = np.asarray(r, float)
    sids = np.asarray(sids)
    ok = ~np.isnan(r)
    r, sids = r[ok], sids[ok]
    if len(r) == 0:
        return {"n": 0}
    out = {"n": int(len(r)), "n_sessions": int(len(set(sids))), "signed": desc(r),
           "median": cq(r, sids, 0.5), "abs": qtab(np.abs(r), sids, (0.5, 0.9, 0.99))}
    if T is not None:
        out["exceed_T_rate"] = crate((np.abs(r) > T).astype(float), np.ones(len(r)), sids)
        out["T_used"] = T
    return out


def fmt_section(P, fmt):
    X = P[P.fmt == fmt]
    C = X[X.clean].reset_index(drop=True)
    sec = {"pairs": int(len(X)), "sessions_with_pairs": int(X.session_id.nunique()),
           "threads": int(X.groupby(["session_id", "thread"]).ngroups),
           "subagent_thread_pairs": int((X.thread != "main").sum()),
           "clean_pairs": int(len(C)), "clean_sessions": int(C.session_id.nunique()),
           "break_flag_counts": {f: int(X[f].sum()) for f in BREAK_FLAGS},
           "desc_flag_counts_clean": {f: int(C[f].sum()) for f in DESC_FLAGS}}
    if len(C) < 200:
        sec["skipped"] = "fewer than 200 clean pairs"
        return sec, None
    s = C.session_id.values
    one = np.ones(len(C))
    sec["out_final_share_clean"] = crate(C.F.values, one, s)
    sec["out_le_10_share_clean"] = crate((C.out_k <= 10).astype(float).values, one, s)
    sec["dC_clean"] = desc(C.dC.values)
    sec["dC_negative_clean"] = crate((C.dC < 0).astype(float).values, one, s)
    neg = C[C.dC < 0]
    sec["dC_negative_clean_concentration"] = {
        "n": int(len(neg)), "n_sessions": int(neg.session_id.nunique()),
        "top5_session_counts": [int(v) for v in neg.session_id.value_counts().head(5).values],
        "C_k_negative": desc(neg.C_k.values), "C_k_all_clean": desc(C.C_k.values)}
    sec["cache_chain_exact_clean"] = crate((~C.d_cache_chain_break).astype(float).values, one, s) \
        if fmt not in FMT_CTX_INCLUDES_CACHE else None
    app = (C.res_chars + C.sys_chars + C.gen_chars).values.astype(float)
    sec["ratio_all_appended_chars_per_dC"] = crate(app, np.maximum(C.dC.values.astype(float), 0), s)
    dom = C[(C.F == 1) & (C.res_n == 1) & (C.sys_n == 0) & (C.res_chars >= 2000)]
    if len(dom) >= 30:
        y = (dom.dC - dom.out_k).values.astype(float)
        sec["single_result_dominated"] = {
            "rule": "F==1, exactly 1 result, no system text, result >= 2000 chars; chars / (dC - out_k)",
            "pooled": crate(dom.res_chars.values.astype(float), np.maximum(y, 0), dom.session_id.values),
            "per_pair": qtab(dom.res_chars.values / np.maximum(y, 1), dom.session_id.values, (0.05, 0.5, 0.95))}
    models, keep = {}, {}
    for model in ("M_hyb", "M_chars", "M_out"):
        r, coefs, bfull, wfull, names, A, y = crossfit(C, model)
        entry = {"coef_full": coef_dict(bfull, names), "coef_fold": {str(f): coef_dict(b, names) for f, b in coefs.items()},
                 "oof_residual": resid_summary(r, s)}
        ci = boot_coef(A, y, wfull, s, names, ["res_chars"])
        if "res_chars" in ci:
            b = entry["coef_full"]["res_chars"]
            entry["res_chars_coef_ci"] = list(ci["res_chars"])
            entry["result_chars_per_token"] = {"value": 1 / b if b > 0 else None,
                                               "lo": 1 / ci["res_chars"][1] if ci["res_chars"][1] > 0 else None,
                                               "hi": 1 / ci["res_chars"][0] if ci["res_chars"][0] > 0 else None}
        models[model] = entry
        keep[model] = (r, coefs, bfull, names)
    sec["models"] = models
    return sec, (C, keep)


def flag_section(P, fmt, C, keep):
    """Non-clean pairs by break flag (scored with the full clean M_hyb fit); clean pairs by descriptive flag (oof)."""
    X = P[P.fmt == fmt]
    r_oof, coefs, bfull, names = keep["M_hyb"]
    T = float(np.nanquantile(np.abs(r_oof), 0.99))
    out = {"T_pooled_q99_abs_oof": T, "break": {}, "descriptive_clean": {}}
    A, _ = design(X, "M_hyb")
    c = dict(zip(names, bfull))
    pred = A @ bfull + c["res_chars"] * X.user_chars.values
    rX = X.dC.values - pred
    nflags = X[BREAK_FLAGS].sum(axis=1).values
    for f in BREAK_FLAGS:
        m = X[f].values
        if m.sum() < PREREG["min_pairs"]["per_flag"]:
            out["break"][f] = {"n": int(m.sum())}
            continue
        e = resid_summary(rX[m], X.session_id.values[m], T)
        e["dC_negative"] = crate((X.dC.values[m] < 0).astype(float), np.ones(int(m.sum())), X.session_id.values[m])
        e["n_only_this_flag"] = int((m & (nflags == 1)).sum())
        out["break"][f] = e
    for f in DESC_FLAGS:
        m = C[f].values
        if m.sum() < PREREG["min_pairs"]["per_flag"] or (~m).sum() < PREREG["min_pairs"]["per_flag"]:
            out["descriptive_clean"][f] = {"n_true": int(m.sum())}
            continue
        out["descriptive_clean"][f] = {"true": resid_summary(r_oof[m], C.session_id.values[m], T),
                                       "false": resid_summary(r_oof[~m], C.session_id.values[~m], T)}
    tools = {}
    st = C[C.n_tools_distinct == 1]
    for tname, g_ in st.groupby("top_tool"):
        if len(g_) < PREREG["min_pairs"]["per_tool"]:
            continue
        idx = g_.index.values
        tools[str(tname)] = resid_summary(r_oof[idx], C.session_id.values[idx], T)
        tools[str(tname)]["window_result_chars"] = desc(g_.res_chars.values)
        tools[str(tname)]["window_result_chars_zero"] = int((g_.res_chars == 0).sum())
        tools[str(tname)]["dC"] = desc(g_.dC.values)
    out["per_tool_single_tool_windows"] = tools
    ex = np.abs(r_oof) > T
    prof = {"n_exceed": int(np.nansum(ex)), "n_exceed_positive": int(np.nansum(ex & (r_oof > 0))),
            "n_exceed_negative": int(np.nansum(ex & (r_oof < 0))), "n_clean": int(len(C)), "flags": {}, "top_tool": {}}
    for f in DESC_FLAGS:
        m = C[f].values
        prof["flags"][f] = {"in_exceed": int((m & ex).sum()), "in_clean": int(m.sum())}
    tt = C.top_tool.fillna("None").astype(str).values
    for tname in pd.Series(tt[ex]).value_counts().head(12).index:
        prof["top_tool"][tname] = {"in_exceed": int(((tt == tname) & ex).sum()), "in_clean": int((tt == tname).sum())}
    out["exceedance_profile"] = prof
    pm = {}
    r_ma = r_oof.copy()
    rate_ma = np.full(len(C), np.nan)
    for f, b in coefs.items():
        m = C.fold.values == f
        rate_ma[m] = eff_rate(C[m], b, names)
    for mname, g_ in C.groupby(C.model_k1.fillna("None")):
        if len(g_) < PREREG["min_pairs"]["per_model_fit"] or g_.session_id.nunique() < 5:
            continue
        r2, coefs2, b2, w2, n2, A2, y2 = crossfit(g_, "M_hyb")
        ci = boot_coef(A2, y2, w2, g_.session_id.values, n2, ["res_chars"])
        bres = dict(zip(n2, b2))["res_chars"]
        idx = g_.index.values
        pm[str(mname)] = {"n": int(len(g_)), "n_sessions": int(g_.session_id.nunique()), "res_chars_coef": float(bres),
                          "res_chars_coef_ci": list(ci["res_chars"]) if "res_chars" in ci else None,
                          "result_chars_per_token": (1 / bres if bres > 0 else None),
                          "coef_full": coef_dict(b2, n2),
                          "oof_residual_pooled_model": resid_summary(r_oof[idx], g_.session_id.values, T),
                          "oof_residual_own_model_fit": resid_summary(r2, g_.session_id.values, T)}
        if len(coefs2) == 2:
            r_ma[idx] = r2
            for f, b in coefs2.items():
                m = g_.fold.values == f
                rate_ma[idx[m]] = eff_rate(g_[m], b, n2)
    out["per_model"] = pm
    out["model_aware_oof_residual"] = resid_summary(r_ma, C.session_id.values)
    # user turns by model (thinking / reasoning retention changes at human turns)
    ut = {}
    mu = X.f_user_turn.values & (nflags == 1)
    for mname in pd.unique(X.model_k1[mu].fillna("None")):
        mm = mu & (X.model_k1.fillna("None").values == mname)
        if mm.sum() >= PREREG["min_pairs"]["per_flag"]:
            ut[str(mname)] = {"n": int(mm.sum()), "median": cq(rX[mm], X.session_id.values[mm], 0.5),
                              "dC_negative": crate((X.dC.values[mm] < 0).astype(float), np.ones(int(mm.sum())), X.session_id.values[mm])}
    out["user_turn_only_by_model"] = ut
    # images: pairs whose only break flag is image and that hold exactly one image marker
    mi = X.f_image.values & (nflags == 1) & ((X.w_img + X.gen_img).values == 1)
    if mi.sum() >= PREREG["min_pairs"]["per_flag"]:
        out["single_image_residual_tokens"] = {"n": int(mi.sum()), "n_sessions": int(X.session_id[mi].nunique()),
                                               "median": cq(rX[mi], X.session_id.values[mi], 0.5), "describe": desc(rX[mi])}
    else:
        out["single_image_residual_tokens"] = {"n": int(mi.sum())}
    return out, (r_ma, rate_ma)


def aiv_cu_gemini_split(P):
    X = P[P.fmt == "aiv_cu:gemini"].copy()
    for c in ("p_text_k", "p_text_k1", "p_image_k", "p_image_k1"):
        X[c] = pd.to_numeric(X[c], errors="coerce")
    X = X[X.p_text_k.notna() & X.p_text_k1.notna()].copy()
    X["p_image_k"] = X.p_image_k.fillna(0)
    X["p_image_k1"] = X.p_image_k1.fillna(0)
    X["dT"] = X.p_text_k1 - X.p_text_k
    X["dI"] = X.p_image_k1 - X.p_image_k
    one = np.ones(len(X))
    out = {"pairs_with_text_image_detail": int(len(X)), "sessions": int(X.session_id.nunique()),
           "text_plus_image_eq_C_k1": int(((X.p_text_k1 + X.p_image_k1) == X.C_k1).sum()),
           "dIMAGE_top_values": {str(int(k)): int(v) for k, v in X.dI.value_counts().head(15).items()},
           "dIMAGE_share_zero": crate((X.dI == 0).astype(float).values, one, X.session_id.values),
           "dIMAGE_share_negative": crate((X.dI < 0).astype(float).values, one, X.session_id.values),
           "dTEXT_share_negative": crate((X.dT < 0).astype(float).values, one, X.session_id.values)}
    units = {}
    for m, g_ in X.groupby(X.model_k1.fillna("None")):
        pp = g_.dI[g_.dI > 0]
        if len(pp) >= 30:
            u = float(pp.mode().iloc[0])
            ni = g_.p_image_k1 / u
            units[str(m)] = {"modal_positive_dIMAGE": u, "n_pairs": int(len(g_)), "n_sessions": int(g_.session_id.nunique()),
                             "share_dI_eq_unit": float((g_.dI == u).mean()), "share_dI_zero": float((g_.dI == 0).mean()),
                             "share_p_image_divisible_by_unit": float(((g_.p_image_k1 % u) == 0).mean()),
                             "images_in_context": desc(ni.values)}
    out["image_unit_by_model"] = units
    unit_of = {m: u["modal_positive_dIMAGE"] for m, u in units.items()}
    um = X.model_k1.fillna("None").map(lambda m: unit_of.get(str(m), np.nan))
    hasu = um.notna()
    out["dIMAGE_in_0_or_unit"] = {"n_pairs_model_with_unit": int(hasu.sum()),
                                  "count": int((((X.dI == 0) | (X.dI == um)) & hasu).sum())}
    out["dIMAGE_positive_by_top_tool"] = {str(t): {"n": int(len(g_)), "dI_positive": int((g_.dI > 0).sum())}
                                          for t, g_ in X.groupby(X.top_tool.fillna("None"))}
    C = X[X.clean].reset_index(drop=True)
    res = {}
    for ycol, lab in (("dT", "TEXT_tokens"), ("dC", "all_prompt_tokens")):
        r, coefs, bfull, wfull, names, A, y = crossfit(C, "M_hyb", ycol)
        res[lab] = {"coef_full": coef_dict(bfull, names), "oof_residual": resid_summary(r, C.session_id.values)}
        ci = boot_coef(A, y, wfull, C.session_id.values, names, ["res_chars"])
        if "res_chars" in ci:
            res[lab]["res_chars_coef_ci"] = list(ci["res_chars"])
        rate = np.full(len(C), np.nan)
        for f, b in coefs.items():
            m = C.fold.values == f
            rate[m] = eff_rate(C[m], b, names)
        res[lab]["detection"] = detection(C, r, rate, C.session_id.values)
    out["text_vs_all_models"] = res
    return out


def codex_saturation(P):
    X = P[(P.fmt == "swechat:codex") & (P.res_n == 1) & (P.sys_n == 0) & (P.user_n == 0) & ~P.f_compaction & (P.F == 1)].copy()
    X["y"] = X.dC - X.out_k
    edges = [0, 1e3, 3e3, 1e4, 2e4, 3e4, 4e4, 6e4, 1e5, 3e5, 1e7]
    X["b"] = pd.cut(X.res_chars, edges, right=False)
    rows = {}
    for b, g_ in X.groupby("b", observed=True):
        rows[str(b)] = {"n": int(len(g_)), "n_sessions": int(g_.session_id.nunique()),
                        "result_chars_median": float(g_.res_chars.median()), "dC_minus_out": desc(g_.y.values)}
    return {"rule": "swechat:codex pairs with exactly one result, no system/user text, no compaction, F==1; y = dC - out_k",
            "bins_result_chars": rows}


def clean_json(o):
    if isinstance(o, dict):
        return {str(k): clean_json(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [clean_json(v) for v in o]
    if isinstance(o, np.integer):
        return int(o)
    if isinstance(o, (np.floating, float)):
        v = float(o)
        return None if (np.isnan(v) or np.isinf(v)) else v
    if isinstance(o, np.bool_):
        return bool(o)
    return o


def main():
    t0 = time.time()
    cache_dir = os.environ.get("TC_PAIRS_CACHE")
    cpath = os.path.join(cache_dir, "pairs.parquet") if cache_dir else None
    if cpath and os.path.exists(cpath):
        P = pd.read_parquet(cpath)
        with open(os.path.join(cache_dir, "counters.json")) as fh:
            counters = json.load(fh)
    else:
        P, counters = extract_all()
        if cpath:
            os.makedirs(cache_dir, exist_ok=True)
            P.to_parquet(cpath)
            with open(os.path.join(cache_dir, "counters.json"), "w") as fh:
                json.dump(clean_json(counters), fh)
    P = derive(P)
    only = os.environ.get("TC_ONLY")
    out = {"prereg": PREREG, "post_hoc": POST_HOC, "build_counters": counters, "fmt": {}}
    for fmt in FMTS:
        if only and fmt not in only.split(","):
            continue
        print("fmt", fmt, round(time.time() - t0, 1), file=sys.stderr)
        sec, kc = fmt_section(P, fmt)
        if kc is not None:
            C, keep = kc
            r, coefs, bfull, names = keep["M_hyb"]
            rate = np.full(len(C), np.nan)
            for f, b in coefs.items():
                m = C.fold.values == f
                rate[m] = eff_rate(C[m], b, names)
            sec["detection_M_hyb"] = detection(C, r, rate, C.session_id.values)
            byt = {}
            st = (C.n_tools_distinct == 1).values
            for tname in pd.unique(C.top_tool[st].astype(str)):
                m = st & (C.top_tool.astype(str).values == tname)
                if m.sum() < 1000:
                    continue
                Cs = C[m].reset_index(drop=True)
                byt[tname] = detection(Cs, r[m], rate[m], Cs.session_id.values)
                byt[tname]["n_pairs"] = int(m.sum())
            sec["detection_M_hyb_by_tool"] = byt
            sec["flags"], (r_ma, rate_ma) = flag_section(P, fmt, C, keep)
            sec["detection_M_hyb_model_aware"] = detection(C, r_ma, rate_ma, C.session_id.values)
        out["fmt"][fmt] = sec
    if not only or "aiv_cu:gemini" in only:
        print("aiv_cu gemini split", round(time.time() - t0, 1), file=sys.stderr)
        out["aiv_cu_gemini_text_image"] = aiv_cu_gemini_split(P)
    out["codex_saturation"] = codex_saturation(P)
    out["runtime_s"] = round(time.time() - t0, 1)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(clean_json(out), fh, indent=1, ensure_ascii=False)
    print("wrote", OUT, round(time.time() - t0, 1), file=sys.stderr)


if __name__ == "__main__":
    main()
